import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { HeartPulse, Search, ChevronDown } from "lucide-react";
import { Link } from "react-router-dom";
import bgArtwork from "../assets/bg-artwork.png";
const Home = () => {
    return (_jsxs("div", { style: {
            minHeight: "100vh",
            width: "100vw",
            position: "relative",
            overflow: "hidden",
            fontFamily: "sans-serif",
            color: "#18181b",
            display: "flex",
            flexDirection: "column",
            backgroundImage: `url(${bgArtwork})`,
            backgroundSize: "cover",
            backgroundPosition: "center",
            backgroundRepeat: "no-repeat",
        }, children: [_jsxs("header", { style: {
                    height: "64px",
                    width: "100%",
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "space-between",
                    padding: "0 40px",
                    backgroundColor: "rgba(255, 255, 255, 0.12)",
                    backdropFilter: "blur(12px)",
                    WebkitBackdropFilter: "blur(12px)",
                    borderBottom: "1px solid rgba(255, 255, 255, 0.3)",
                    zIndex: 30,
                    boxSizing: "border-box",
                }, children: [_jsxs("div", { style: {
                            display: "flex",
                            alignItems: "center",
                            gap: "10px",
                        }, children: [_jsx("div", { style: {
                                    width: "32px",
                                    height: "32px",
                                    borderRadius: "50%",
                                    backgroundColor: "#18181b",
                                    display: "flex",
                                    alignItems: "center",
                                    justifyContent: "center",
                                }, children: _jsx(HeartPulse, { size: 18, color: "#ffffff" }) }), _jsxs("span", { style: {
                                    fontWeight: 700,
                                    fontSize: "16px",
                                    letterSpacing: "-0.5px",
                                }, children: ["Health", _jsx("span", { style: { color: "#0d9488" }, children: "AI" })] })] }), _jsxs("div", { style: {
                            display: "flex",
                            alignItems: "center",
                            gap: "16px",
                        }, children: [_jsxs("div", { style: {
                                    display: "flex",
                                    alignItems: "center",
                                    gap: "8px",
                                    backgroundColor: "rgba(255, 255, 255, 0.25)",
                                    padding: "6px 14px",
                                    borderRadius: "20px",
                                    border: "1px solid rgba(255, 255, 255, 0.4)",
                                }, children: [_jsx(Search, { size: 14, color: "#334155" }), _jsx("input", { type: "text", placeholder: "Search", style: {
                                            border: "none",
                                            outline: "none",
                                            background: "transparent",
                                            fontSize: "12px",
                                            width: "80px",
                                        } })] }), _jsxs("div", { style: {
                                    display: "flex",
                                    alignItems: "center",
                                    gap: "4px",
                                    fontSize: "12px",
                                    fontWeight: 500,
                                    color: "#334155",
                                    cursor: "pointer",
                                }, children: [_jsx("span", { children: "English (United States)" }), _jsx(ChevronDown, { size: 14 })] }), _jsx(Link, { to: "/login", style: {
                                    padding: "6px 18px",
                                    borderRadius: "20px",
                                    border: "1px solid rgba(255, 255, 255, 0.5)",
                                    backgroundColor: "rgba(255, 255, 255, 0.2)",
                                    fontSize: "12px",
                                    fontWeight: 600,
                                    color: "#0f172a",
                                    textDecoration: "none",
                                }, children: "Log in" }), _jsx(Link, { to: "/register", style: {
                                    padding: "6px 18px",
                                    borderRadius: "20px",
                                    backgroundColor: "#09090b",
                                    fontSize: "12px",
                                    fontWeight: 600,
                                    color: "#ffffff",
                                    textDecoration: "none",
                                }, children: "Sign up" })] })] }), _jsx("div", { style: {
                    flex: 1,
                    display: "flex",
                    alignItems: "center",
                    padding: "0 80px",
                    zIndex: 10,
                }, children: _jsxs("div", { style: {
                        width: "520px",
                        padding: "52px",
                        borderRadius: "36px",
                        backgroundColor: "rgba(255, 255, 255, 0.03)",
                        backdropFilter: "blur(8px) contrast(105%)",
                        WebkitBackdropFilter: "blur(8px) contrast(105%)",
                        border: "1px solid rgba(255, 255, 255, 0.55)",
                        boxShadow: "0 20px 40px rgba(0, 0, 0, 0.03), inset 0 1px 2px rgba(255, 255, 255, 0.4)",
                        boxSizing: "border-box",
                    }, children: [_jsxs("h1", { style: {
                                fontSize: "44px",
                                fontWeight: 800,
                                lineHeight: "1.12",
                                margin: 0,
                                color: "#09090b",
                                letterSpacing: "-1.2px",
                            }, children: ["Understand your ", _jsx("br", {}), "health. ", _jsx("br", {}), "Explore with us"] }), _jsx("p", { style: {
                                marginTop: "24px",
                                marginBottom: "36px",
                                fontSize: "14px",
                                lineHeight: "1.65",
                                color: "#334155",
                                maxWidth: "380px",
                                fontWeight: 500,
                            }, children: "HealthAI helps you track symptoms, organize health records, and discover personalized wellness insights \u2014 all in one secure platform." }), _jsxs("div", { style: {
                                display: "flex",
                                alignItems: "center",
                                backgroundColor: "rgba(255, 255, 255, 0.18)",
                                backdropFilter: "blur(12px)",
                                WebkitBackdropFilter: "blur(12px)",
                                border: "1px solid rgba(255, 255, 255, 0.6)",
                                borderRadius: "40px",
                                padding: "4px 4px 4px 18px",
                                maxWidth: "380px",
                                boxShadow: "0 4px 15px rgba(0, 0, 0, 0.02)",
                            }, children: [_jsx("input", { type: "email", placeholder: "Enter your email address", style: {
                                        flex: 1,
                                        border: "none",
                                        outline: "none",
                                        background: "transparent",
                                        fontSize: "13px",
                                        color: "#0f172a",
                                        fontWeight: 500,
                                    } }), _jsx(Link, { to: "/register", style: {
                                        backgroundColor: "#09090b",
                                        color: "#ffffff",
                                        border: "none",
                                        borderRadius: "30px",
                                        padding: "10px 24px",
                                        fontSize: "13px",
                                        fontWeight: 600,
                                        cursor: "pointer",
                                        textDecoration: "none",
                                        whiteSpace: "nowrap",
                                    }, children: "Sign up" })] })] }) })] }));
};
export default Home;
